---
type: containerfile
snippets:
  - COPY --from=cgr.dev/chainguard/dive:latest /usr/bin/dive /usr/bin/dive
  - COPY --from=cgr.dev/chainguard/helm:latest /usr/bin/helm /usr/bin/helm
  - COPY --from=cgr.dev/chainguard/kubectl:latest /usr/bin/kubectl /usr/bin/kubectl
