---
name: build silverblue
on:
  schedule:
    - cron: "00 18 * * */2"
  pull_request:
  workflow_dispatch:
jobs:
  bluebuild:
    name: ublue image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - silverblue.yml
    steps:
      - name: Build Custom Image
        uses: blue-build/github-action@v1.8
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          rechunk: true
          maximize_build_space: true
